from .delete_product import DeleteProductInterface
from .get_products import GetProductsByDayInterface
from .get_week_days import WeekDaysInterface
from .register_product import RegisterProductInterface
from .update_product_status import UpdateProductStatusInterface
