version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
  api:
    container_name: thaixys
    build:
      context: ./
    image: api-image
    ports:
      - 5001:5001
    depends_on:
      - db
    volumes:
      - './:/app'

volumes:
  db:
    driver: local
