from .delete_product import DeleteProductController
from .get_products_by_day import GetProductsByDayController
from .register_product import RegisterProductController
from .update_product_status import UpdateProductStatusController
